### PR TITLE
Fixed implementation so that effort_controllers/GripperActionController works.

### LINKED ISSUE #694: effort_controllers/GripperActionController send position command instead of effort command
**Describe the bug**
effort_controllers/GripperActionController send position command instead of effort command 
and not work correctly for me.

**To Reproduce**
1. Set  effort_controllers/GripperActionController in yaml like this
```yaml
controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    gripper_controller:
      type: effort_controllers/GripperActionController

gripper_controller:
  ros__parameters:
    action_monitor_rate: 200.0
    joint: joint1
    goal_tolerance: 0.01
    max_effort: 0.05
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 2.0
    gains:
      gripper_joint: {p: 200, d: 1, i: 5, i_clamp: 1}
```
2. Load setting in launch file like this
```
    gripper_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["gripper_controller", "--controller-manager", "/controller_manager"],
    )
```
3. Run `ros2 control view_controller_chains` command and check interfaces.

**Expected behavior**
I think effort_controllers/GripperActionController should have effort command interface and position and velocity state interface.

**Screenshots**
This shows gripper_controller uses the position command interface.
image

**Environment (please complete the following information):**
 - OS: Ubuntu22.04
 - Version Humble

**Additional context**
hw_iface_adapter_ template is determined by the type of joint_position_command_interface_, but it looks like an implementation where position_command_interface_it is always HW_IF_POSITION

https://github.com/ros-controls/ros2_controllers/blob/76b1ce7da5e7a102ef3a1c8c4f1b0de90ed0d137/gripper_controllers/include/gripper_controllers/gripper_action_controller_impl.hpp#L281-L286

https://github.com/ros-controls/ros2_controllers/blob/76b1ce7da5e7a102ef3a1c8c4f1b0de90ed0d137/gripper_controllers/include/gripper_controllers/gripper_action_controller_impl.hpp#L229-L232

### PR DESCRIPTION
**Pull request by chama1176**
Fixed implementation so that effort_controllers/GripperActionController works.

Fixed #694

### CODE REVIEW

**Comment by chama1176** [comment]
@bmagyar 
Could you advise me on the merge request?
Is there any chance to merge?

**Review by christophfroehlich — COMMENTED** [review]
Thanks for your contribution. It looks good to me, but we'll see if CI is happy if one of the @ros-controls/ros2-maintainers approves the workflows.

We should definitely add tests for that to improve the gripper_controller. @chama1176 Could you have a look on that? I suggest copying the parameterized tests from joint_trajectory_controller, so that we run all tests with position and effort interface.

**Review by bmagyar — APPROVED** [review]
thank you for finishing the implementation of this, I don't know how come we didn't discover this earlier... :facepalm:

**Comment by christophfroehlich** [comment]
I opened a new issue for adding tests. @bmagyar can we backport this to humble?

**Pull request merged**
