### PR TITLE
Fix frame id in diff_drive_controller (#521)

### PR DESCRIPTION
**Pull request by tverbele**
Strips first "/" from namespace and only append once.

### CODE REVIEW

**Review by destogl — COMMENTED** [review]
Thanks! The old code seems odd. Now, sure, if there were a specific reason to do that.

I agree, but the code looks strange/complicated in general. Can we write a test – to understand how this is used at all.

**Comment by bmagyar** [comment]
... or at least document how you can get the current setup to fail

**Review by bmagyar — APPROVED** [review]
TBH the erase line could do with a comment to document it a bit but I think that the appending of namespaces is the result of a conflict resolution gone wrong @destogl , those lines are just plain dumb, we should merge this asap

**Review by destogl — APPROVED** [review]
Thanks!

**Pull request merged**
