### PR TITLE
Compute velocity errors when using an effort command interface

### PR DESCRIPTION
**Pull request by tingelst**
This PR is in reference to the discussion in issue https://github.com/ros-controls/ros2_controllers/issues/673#issue-1760444492. The changes in https://github.com/ros-controls/ros2_controllers/commit/8e6697b introduced a bug in that the velocity error terms was not computed when using an effort command interface, resulting in a wobbly/jerky motion. This PR fixes this issue.

### CODE REVIEW

**Comment by bmagyar** [comment]
Do you have a good idea for adding a test for this? To avoid making this mistake in the future

**Review by christophfroehlich — COMMENTED** [review]
I think this is fine. But I'm not sure if #491 really introduced this, the velocity error wasn't calculated before with effort command interface?

**Comment by tingelst** [comment]
The velocity error was calculated before, but it was done directly in the `computeCommand` as seen [here](https://github.com/ros-controls/ros2_controllers/pull/491/commits/54509970861c86f413959f92d1a2da49adc0bd94#diff-8dd2135dc1f4abe6382cc7671ef9ce939196b2d8adf18ac3a77b5c0fddf1a25fL247).

**Comment by christophfroehlich** [comment]
> The velocity error was calculated before, but it was done directly in the `computeCommand` as seen [here](https://github.com/ros-controls/ros2_controllers/pull/491/commits/54509970861c86f413959f92d1a2da49adc0bd94#diff-8dd2135dc1f4abe6382cc7671ef9ce939196b2d8adf18ac3a77b5c0fddf1a25fL247).

I see, sorry. I thought I removed the redundant difference calculation only, but hadn't had the effort interface in mind.

**Comment by christophfroehlich** [comment]
I've written a test and made the PR #690 against _jtc-features_ branch, where the effort tests are active already. It failed before I cherry-picked the commit from this PR. Let the maintainers decide if we merge the test directly to _master_ or wait for _jtc-features_ to be merged.

**Comment by christophfroehlich** [comment]
@destogl this is already included in #705 (I squashed the changes, this is why it shows new commits but no changes)

**Comment by destogl** [comment]
OK, I'll then close this, OK?

**Pull request closed without merging**
