### PR TITLE
Removing explicit Boost disable for controllers

### PR DESCRIPTION
**Pull request by bailaC**
Further changes for Controllers. This will remove the restriction for Boost from Controllers.

ros2_control PR : https://github.com/ros-controls/ros2_control/pull/514

### CODE REVIEW

**Comment by bailaC** [comment]
@destogl , @bmagyar , Please take a look.

**Comment by bmagyar** [comment]
I'd ask to update the title. We are not enabling boost dependencies since we do not depend on them. What changed is that we do not need to explicitly disable boost with pluginlib anymore as that is the default. It will remain disabled.

**Comment by bailaC** [comment]
Title updated.

**Review by destogl — APPROVED** [review]
Looks good thanks!

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
