### PR TITLE
Fix bug for displaying all controllers

### PR DESCRIPTION
**Pull request by fmrico**
Hi,

When using the rqt_joint_trajectory_controller, not all the controllers are shown on the controller button. This is because the list of limits was not accumulated, and only the last one was considered. This PR fixes this, showing all the valid controllers.

I hope it helps
Francisco

### CODE REVIEW

**Review by saikishor — APPROVED** [review]
LGTM

**Comment by saikishor** [comment]
@fmrico can you apply the pre-commit formatting changes

**Comment by fmrico** [comment]
Hi @saikishor !! Changes applied. Let's wait for CI

**Comment by bmagyar** [comment]
and let's see the CI after Christop's updates ;)

**Pull request merged**
