### PR TITLE
[JTC] Fix typos, implicit cast, const member functions

### PR DESCRIPTION
**Pull request by christophfroehlich**
Fix typos, implicit cast warnings, and declare const member functions as const

### CODE REVIEW

**Review by saikishor — APPROVED** [review]
LGTM

**Comment by saikishor** [comment]
It is weird that CI says that the changes break ABI. I don't see any ABI breaking changes. 

Thanks for the changes

**Comment by christophfroehlich** [comment]
> It is weird that CI says that the changes break ABI. I don't see any ABI breaking changes.

I guess that the const qualifiers change ABI?

`has_active_trajectory` from #558 has not been released until now, and the other methods are for testing only -> don't see any problem changing this now.

**Review by bmagyar — APPROVED** [review]
Very good, thank you!

**Pull request merged**
