### PR TITLE
Use a single file for migration + release notes

### PR DESCRIPTION
**Pull request by christophfroehlich**
we decided to show only the notes for the respective version in the docs, instead of all incremental distro upgrades

this makes backports easier and should avoid merge conflicts in the docs.

needs https://github.com/ros-controls/control.ros.org/pull/324

### CODE REVIEW

**Review by olivier-stasse — APPROVED** [review]
LGTM

**Comment by olivier-stasse** [comment]
The CI is giving a strange error message while there are only 2 warnings and no visible error.

**Comment by christophfroehlich** [comment]
> The CI is giving a strange error message while there are only 2 warnings and no visible error.

That's normal, the CI job considers warnings as errors and fails if it doesn't find files for example.

**Review by saikishor — APPROVED** [review]
LGTM!

**Pull request merged**
