### PR TITLE
Don't run humble workflows from master branch

### PR DESCRIPTION
**Pull request by bmagyar**

### CODE REVIEW

**Comment by destogl** [comment]
If we remove all of those, then we will lose scheduled builds for those versions. Only the default branch can execute scheduled builds. This means that master needs to have all actions, which are then filtered by triggers at the beginning of the definition.

**Comment by bmagyar** [comment]
I've retargeted all humble workflows to the humble branch.

**Review by destogl — APPROVED** [review]
Thanks!

**Comment by moriarty** [comment]
@Mergifyio backport humble

**Pull request merged**
