### PR TITLE
fix parallel_gripper_controller failing tests

### PR DESCRIPTION
**Pull request by saikishor**
The Parallel gripper controller tests are not passing on the rolling from beginning, I've modified the tests to make it work. However, I had to remove a couple of tests as in the GPL the parameter `joint` is declared as `read_only`, and this makes most of the tests doesn't work at all, so I've cleaned them up 

https://github.com/ros-controls/ros2_controllers/blob/0bb88805713fb21cddc418bc4c502960d9fd9f39/parallel_gripper_controller/src/gripper_action_controller_parameters.yaml#L11-L14

### CODE REVIEW

**Review by christophfroehlich — COMMENTED** [review]
Should we use GPL for validation instead of checking `params_.joint.empty()`? Then there is no need for testing it (see the deleted tests).

**Review by destogl — CHANGES_REQUESTED** [review]
Agree with @christophfroehlich, let's use `GenerateParameterLiberry` validators instead of testing empty joints.

**Review by christophfroehlich — APPROVED** [review]
Thanks for the changes (haven't tested it with #1206, but I guess you did?)

**Review by destogl — APPROVED** [review]
Thanks!

**Pull request merged**
