### PR TITLE
Deprecate non-stamped twist for tricycle_controller and steering_controllers

### PR DESCRIPTION
**Pull request by christophfroehlich**
First step of #989.

### CODE REVIEW

**Review by aprotyas — APPROVED** [review]

**Review by olivier-stasse — APPROVED** [review]
LGTM

Just a small remark, it will not be possible to send directly a command to a robot using DiffDrive controller from a console.

That was nice to switch easily from turtlesim to a real robot from a pedagogical point of view. But the auto completion in ROS-2 with pub topic is not working super nicely from my experience. If anybody has a nice way to have a simple example for `ros2 topic pub /cmd_vel`, it will be nice to document it.

**Comment by christophfroehlich** [comment]
> Just a small remark, it will not be possible to send directly a command to a robot using DiffDrive controller from a console.
> 
> That was nice to switch easily from turtlesim to a real robot from a pedagogical point of view. But the auto completion in ROS-2 with pub topic is not working super nicely from my experience. If anybody has a nice way to have a simple example for `ros2 topic pub /cmd_vel`, it will be nice to document it.

You mean because it is not possible to auto-fill the time-stamp in the header? Or that the syntax of the nested msg is tedious?

**Comment by olivier-stasse** [comment]
> You mean because it is not possible to auto-fill the time-stamp in the header? Or that the syntax of the nested msg is tedious? https://control.ros.org/master/doc/ros2_control_demos/example_2/doc/userdoc.html

Actually both. (BTW thanks again for the documentation effort this is great !) With the auto completion I never  managed to have the nice example you gave in the docs. I do not remember if there is a default acceptable value for the time stamp like 0 for all the fields.

**Review by saikishor — APPROVED** [review]
LGTM. Do we want to completely remove it in Jazzy or leave it with a deprecation warning? 

I agree with @olivier-stasse. I believe it should be fine to publish with 0 timestamp as it is usually considered as the  command sent with the current timestamp

**Comment by christophfroehlich** [comment]
> LGTM. Do we want to completely remove it in Jazzy or leave it with a deprecation warning?
> 
Yes, I think we will completely remove it. I'm not sure if there will be a rolling release before jazzy, but I thought at least we can backport the deprecation warning to iron. 

> I agree with @olivier-stasse. I believe it should be fine to publish with 0 timestamp as it is usually considered as the command sent with the current timestamp

Is this a feature of ROS 2 CLI or does the controller just have to "ignore" zero timestamp? I'd have to test that

**Comment by christophfroehlich** [comment]
> Actually both. (BTW thanks again for the documentation effort this is great !) 
:smile: 

> With the auto completion I never managed to have the nice example you gave in the docs. I do not remember if there is a default acceptable value for the time stamp like 0 for all the fields.

I also struggle always there. Sometimes it's faster to ask my AI friend for the syntax than trying around..

**Comment by saikishor** [comment]
> Is this a feature of ROS 2 CLI or does the controller just have to "ignore" zero timestamp? I'd have to test that

I think the controller is the one who has to consider the zero timestamps as the recent one. Upon checking the code, this is already handled. In fact in most of the ROS/ROS2 systems it is considered like that

https://github.com/ros-controls/ros2_controllers/blob/689efe716fd97f4c79638689ececc65fe175b418/diff_drive_controller/src/diff_drive_controller.cpp#L344-L351

**Comment by bmagyar** [comment]
I think the clunkiness comes from the CLI auto complete offering a one-lined yaml as opposed to the JSON format (dict with curly brackets)

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
