### PR TITLE
[JTC] Use the same variables for state feedback and PID loop

### PR DESCRIPTION
**Pull request by christophfroehlich**
Before this change, the published `state.position.error` was normalized by `angles::shortest_angular_distance` but the position error for the PID loop was not.

### CODE REVIEW

**Review by destogl — APPROVED** [review]
Generally yes, when CI is also happy.

Could it be that `state_error_` is calculated after this lines? Maybe this is the reason of failing CI at the moment.

**Comment by christophfroehlich** [comment]
The only thing failing is the binary build, or am I missing something?

>  ERROR: the following rosdeps failed to install
>   dnf: Failed to detect successful installation of [ros-rolling-generate-parameter-library]
>   dnf: Failed to detect successful installation of [ros-rolling-rsl]

**Comment by christophfroehlich** [comment]
#491 includes this change and does not change the default behavior (in contrast to this PR).

**Comment by bmagyar** [comment]
closing in favour of #491

**Pull request closed without merging**
