### PR TITLE
enable ReflowComments to also use ColumnLimit on comments

### PR DESCRIPTION
**Pull request by saikishor**
Currently, as the ReflowComments are not enabled, the 100 columns limit is only applied to the code but not to the comments, and in the end, the CI checks are failing in this regard. By enabling the ReflowComments, this should be solved

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]
Formatters be formatting

Thanks!

**Review by christophfroehlich — APPROVED** [review]
Approving the changes, but now someone has to reformat this repo ;)

**Comment by saikishor** [comment]
> Approving the changes, but now someone has to reformat this repo ;)

Sure. Let me reformat it and push in the same PR

**Comment by saikishor** [comment]
@christophfroehlich @bmagyar Do you think it is better to merge this as it is and create a different PR for humble and rolling with the reformatted changes? or shall I add the reformatted changes to the same PR?. I'm just asking w.r.t backport conflicts

**Comment by saikishor** [comment]
Hello @christophfroehlich @bmagyar 
There are some differences between `rolling` and `humble`, It wouldn't be back portable directly. I have created 2 different PRs for each branch

**Review by bmagyar — APPROVED** [review]
Thank you!

**Pull request merged**
