### PR TITLE
[Ready] Port over interpolation formulae, abort if goals tolerance violated

### PR DESCRIPTION
**Pull request by ddengster**
Siphoned from #36 

Addresses issue #30 

Things done:
- interpolation formulae ported over from ros1
- sample() and interpolation() functions emit  velocities and accelerations properly
- tests fixed accordingly due to parameter "stopped_velocity_tolerance" breaking them
- abort due to goal tolerance violation fixed

### CODE REVIEW

**Comment by Karsten1987** [comment]
this has to be rebased

**Comment by bmagyar** [comment]
I'll take care of it

**Comment by ddengster** [comment]
@bmagyar 
Thanks for taking care of the rebase. In general I think it'll be better for #68 to be fixed and go in first before this PR. I believe there are also a number of tests that have to be updated.

**Comment by ddengster** [comment]
@bmagyar @v-lopez So it seems there are a couple of updates in ros2_control that were intended for foxy that have propagated to the tests. I'm unable to compile them because I'm still on eloquent, and have to stay there for work reasons. Perhaps some of you would like to take over this PR for foxy? 

The only changes is to make sure it's somewhat compatible with the partial joints PR and that the tests are updated.

**Comment by v-lopez** [comment]
I'll try to give it a shot tomorrow.

**Comment by v-lopez** [comment]
I've tested with a docker from `osrf/ros2:nightly` and with the latest ros2_control and this branch I am able to compile and run all JTC tests succesfully.

The interaction with the partial joints should be straightforward, because your changes affect the Trajectory class, where the partial goals have been converted to full goals.

Is there anything I am missing?

**Comment by ddengster** [comment]
> Is there anything I am missing?

There were a number of changes in test_trajectory_actions.cpp and when this [refactor test cases PR](https://github.com/ros-controls/ros2_controllers/pull/64/files) came up. But I've looked at it and it seems fine. So LGTM

**Pull request merged**
