### PR TITLE
Changing to_chrono to use nanoseconds

### PR DESCRIPTION
**Pull request by danwahl**
Previously std::chrono::seconds, which rounds to 0 if action_monitor_period_ < 1

### CODE REVIEW

**Comment by nbbrooks** [comment]
A [related bugfix with JTC](https://github.com/ros-controls/ros2_controllers/pull/437) also resets the timer pointer so you don't end up creating multiple ones. It's a shame noone caught the pattern being used here in gripper controller.

**Review by destogl — APPROVED** [review]
Thanks for this fix!

**Review by mcbed — APPROVED** [review]

**Review by bmagyar — APPROVED** [review]
Nice catch, thanks for the follow-up!

**Comment by bmagyar** [comment]
@mergifyio backport to humble

**Pull request merged**
