### PR TITLE
Fixes tests to work with use_global_arguments NodeOptions parameter 

### PR DESCRIPTION
**Pull request by saikishor**
Needs: https://github.com/ros-controls/ros2_control/pull/1701

Fixes: https://github.com/ros-controls/ros2_controllers/issues/1252
Fixes: https://github.com/ros-controls/ros2_controllers/issues/1253
Fixes: https://github.com/ros-controls/ros2_controllers/issues/1254
Fixes: https://github.com/ros-controls/ros2_controllers/issues/1255

### CODE REVIEW

**Review by christophfroehlich — COMMENTED** [review]
why don't we need the changes for admittance controller and range_sensor_broadcaster?
the tests succeed, which means that they load successfully without parameters? 
Shouldn't we check if they initialized properly?
```
1: [ERROR] [1724184278.166220317] [load_admittance_controller]: Exception thrown during init stage with message: parameter 'joints' is not initialized 
1: 
1: [ERROR] [1724184278.166266164] [test_controller_manager]: Could not initialize the controller named 'load_admittance_controller'
1: [       OK ] TestLoadAdmittanceController.load_controller (40 ms)
```

range_sensor_broadcaster initializes fine, I guess it doesn't need non-default parameters.

**Comment by saikishor** [comment]
@christophfroehlich it's probable that they are returning successful even without parameters. That's the only explanation. I could try fixing them tomorrow.

**Comment by christophfroehlich** [comment]
> @christophfroehlich it's probable that they are returning successful even without parameters. That's the only explanation. I could try fixing them tomorrow.

but it throws the exception, and CM::add_controller_impl should return nullptr..

Furthermore,  I'm not sure why load_JTC succeeds. it should throw an error without paramaters, but I only see 
```
1: [INFO] [1724185010.487326696] [test_controller_manager]: Subscribing to '/robot_description' topic for robot description.
1: [INFO] [1724185010.487412910] [test_controller_manager]: Loading controller 'test_joint_trajectory_controller'
1: [ERROR] [1724185010.496710000] [test_joint_trajectory_controller]: Unable to start transition 5 from current state shuttingdown: Could not publish transition: publisher's context is invalid, at ./src/rcl/publisher.c:423, at ./src/rcl_lifecycle.c:368
1: [WARN] [1724185010.496722342] [rclcpp_lifecycle]: Shutdown error in destruction of LifecycleNode: final state(unconfigured)
1: [       OK ] TestLoadJointStateController.load_controller (40 ms)
```

This is not really linked to this PR here. I suggest applying the same changes to admittance_ctrl and range_sensor_broadcaster (the only controllers using a yaml file which are not already addressed) and create a follow-up issue for those false-positive tests.

**Comment by saikishor** [comment]
Ok. I'm outside right now. I'll try to do that sooner

**Comment by saikishor** [comment]
@christophfroehlich applied the fix to both the controllers as well

**Review by christophfroehlich — APPROVED** [review]
LGTM

**Review by bmagyar — APPROVED** [review]
Thank you!

**Pull request merged**
