### PR TITLE
Add mobile robot kinematics 101 and improve steering library docs

### PR DESCRIPTION
**Pull request by christophfroehlich**
This is the first step of #931, but I focused only on steering on the front axle for now.
Edit: I also added the diff-drive kinematics to have a complete documentation.

After peer-reviewing of the equations I'd start to rename the variables of the library to match the doc and fix possible bugs. 

# rendered docs (updated [5d6aee7](https://github.com/ros-controls/ros2_controllers/pull/954/commits/5d6aee7be2cc8767667563803cf5b7f9fc8868b3))
image

### CODE REVIEW

**Comment by christophfroehlich** [comment]
:eyes: @aleksandrsizmailovs @roncapat @franzrammerstorfer @petkovich

**Comment by christophfroehlich** [comment]
Ad odometry of ackermann steering: There is a not negligible error imho. (average is the equation implemented in the library, plotted for l = 1, w = 1; the equation from above gives the correct angle phi)
image

**Comment by roncapat** [comment]
Impressive job! I think this is very valuable. At least for now everything seems ok to me, I would maybe suggest to be more explicit in the derivation of some formulas, maybe with collapsable sections.

For example, for the unicycle:
immagine this implies at least one or two intermediate steps and to make the description more appealing to readers I may tend to add detail (so the attention of the reader is shifted from understanding the formulas to trusting them) even if sometimes it seems trivial :)

The point is... there are not so many places on the internet where you can find a clean explanation. This can become one of these 👍🏻

About the "overdetermined" odometry solution of ackermann with traction, I would start to think about a set of recommendations or methods to find the best solution. It gets even worse with 4-wheel-4-steer vehicles and becomes an hell when considering mars-like rovers (6 wheeled).

**Comment by christophfroehlich** [comment]
> Impressive job! I think this is very valuable. At least for now everything seems ok to me, I would maybe suggest to be more explicit in the derivation of some formulas, maybe with collapsable sections.
> 
> For example, for the unicycle: immagine this implies at least one or two intermediate steps and to make the description more appealing to readers I may tend to add detail (so the attention of the reader is shifted from understanding the formulas to trusting them) even if sometimes it seems trivial :)
> 
> The point is... there are not so many places on the internet where you can find a clean explanation. This can become one of these 👍🏻

Thanks! I was not sure where to start and where to end. I think about it.

> About the "overdetermined" odometry solution of ackermann with traction, I would start to think about a set of recommendations or methods to find the best solution. It gets even worse with 4-wheel-4-steer vehicles and becomes an hell when considering mars-like rovers (6 wheeled).

We should at least assume, that ever actuated joint has a feedback sensor (e.g., no combination of traction joints on the rear axle but speed sensors on the front axle) -> this would get very complicated to parameterize for every combination.

But as far as I understood: the claim of this lib at the current state was bicycle, tricycle, ackermann; all with front or back steering; and with the traction axle being the other than the steering axle? (the steering+traction ackermann description is not part of this then, but part of this proposal of a "general" library https://github.com/ros-controls/ros2_controllers/issues/692#issuecomment-1749748573)
This is the first real difference to the tricycle_controller for #850, which expects the steering wheel be the only traction wheel, and the two behind are just following.

**Comment by christophfroehlich** [comment]
Am I right that for a trailing steering axis (`front_steering=false`) one has just to use a negative value for the wheel-base `l`, and that's it?

**Comment by bmagyar** [comment]
@petkovich this may be interesting to you

**Comment by MCFurry** [comment]
Very nice @christophfroehlich this looks like a very good documentation page! Nice work!
Looks alright to me.
IMHO I would finish and merge this PR. 
The documentation page will then be available to the public and more sets of eyes can look at it and possibly spot errors or recommend improvements?

**Comment by christophfroehlich** [comment]
> Very nice @christophfroehlich this looks like a very good documentation page! Nice work! Looks alright to me. IMHO I would finish and merge this PR. The documentation page will then be available to the public and more sets of eyes can look at it and possibly spot errors or recommend improvements?

Thanks! Would you mind adding a review in the UI? (Below "Files Changed" tab -> Review Changes). Yes, this will be published on control.ros.org.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
