### PR TITLE
Add diff drive

### PR DESCRIPTION
**Pull request by brightenlee**
It was ported except for some parts.

### CODE REVIEW

**Comment by bmagyar** [comment]
I've changed the target to be master, now we have a proper diff. 

Can you elaborate on "except for some parts" please?

**Comment by brightenlee** [comment]
Importing wheel parameters from URDF and dynamic_reconfigure

**Comment by bmagyar** [comment]
Thanks! One of the things we'd like to do is to change licensing for Apache 2 as with the rest of ROS2. Would you mind removing your own credits to make life easier? We tend to not claim credits for porting unless it's a substantial rewrite effort.

The plan is to work more on the diff drive port by @piraka9011 hopefully and once all the code is in, have *one PR* where we get confirmation from all past authors that the license can be changed. All nice and lawyers are happy.

**Comment by brightenlee** [comment]
Sure. I'm glad to be able to contribute even a little.

**Comment by Karsten1987** [comment]
@brightenlee What's the status of this PR? Are you continuing to work on this or can this be closed?

**Pull request closed without merging**
