### PR TITLE
Fix deprecation warning in paramater declaration

### PR DESCRIPTION
**Pull request by kumar-sanjeeev**
Updated the paramater declaration in `publisher_forward_position_controller` to resolve a deprecation warning when running the demo using  `ros2 launch ros2_control_demo_example_1 test_forward_position_controller.launch.py`.

Changes Made:
- Replaced `self.declare_parameter(name)` with `self.declare_parameter(name, descriptor=ParameterDescriptor(dynamic_typing=True))`

Fixes: #1239

### CODE REVIEW

**Review by christophfroehlich — COMMENTED** [review]
Thanks for your contribution. 
One question: Why shouldn't we specify the type of being a `PARAMETER_STRING` instead of activating `dynamic_typing`?

**Comment by kumar-sanjeeev** [comment]
Hi @christophfroehlich 

Yes, that is another way to suppress the warnings. I opted for `dynamic_typing` because  same is implemented in the `publisher_joint_trajectory_controller`.

I also tried specifying the type, and it is doing the job: `self.declare_parameter(name, rclpy.Parameter.Type.STRING)`.

**Comment by destogl** [comment]
> As you suggested, I tried using the type during the declaration of parameters, and it works as well: `self.declare_parameter(name, rclpy.Parameter.Type.DOUBLE_ARRAY)`

Let's use this exact approach. As rather to use `explicit` instead of `implicit`

**Review by bmagyar — APPROVED** [review]

**Review by christophfroehlich — APPROVED** [review]
LGTM!

**Review by saikishor — APPROVED** [review]
LGTM

**Pull request merged**
