### PR TITLE
Iron to use kimatics interface from Humble

### PR DESCRIPTION
**Pull request by bmagyar**

### CODE REVIEW

**Comment by christophfroehlich** [comment]
@bmagyar or any chance to backport this https://github.com/ros-controls/ros2_controllers/pull/1354?

**Review by saikishor — COMMENTED** [review]
May be it is better to branch of from last released version of ros2-master, or we can work on a minor changes to the kinematics_interface that way it works on both Iron and the latest distros

**Review by christophfroehlich — APPROVED** [review]
Whatever you decide, please change this on the master branch and backport to humble+iron to keep stuff in sync.
fyi: This has to be changed then as well
https://github.com/ros-controls/ros2_control_ci/blob/master/ros_controls.iron.repos

**Comment by bmagyar** [comment]
You guys are correct, we should backport the recent changes

**Pull request closed without merging**
