### PR TITLE
Add a `passthrough_controller` demo

### PR DESCRIPTION
**Pull request by AndyZe**
This is a simple demo of a chained controller that I'm working on with @saikishor

### CODE REVIEW

**Comment by bmagyar** [comment]
@christophfroehlich @ARK3r do you guys think this'd be better hosted in the demos repo?

**Comment by ARK3r** [comment]
I honestly don't know enough about use cases for this, but I think it could be useful to demonstrate how to write a custom controller perhaps.

**Comment by saikishor** [comment]
> I honestly don't know enough about use cases for this, but I think it could be useful to demonstrate how to write a custom controller perhaps.

Hello @ARK3r,

With @AndyZe, we wrote this controller in order to have it as a tutorial/demo on how to write a chainable controller. This is a simple controller that simply takes the interface and forwards the interface to another controller. It is purely written for demonstration. 

As we always have the controller name prepended to the exported interfaces, as in the interface `/controller_1/position_x` will be exposed as `/passthrough_controller/controller_1/position_x`, I don't think we will have a lot of use cases with this. In the future, we might modify it to expose it without the initial controller naming, then it might be useful.

**Comment by christophfroehlich** [comment]
In this case I vote for the demo repository. I also proposed a GPIO controller there, where the use-case is kind of similar to this one (demonstration only).

**Comment by saikishor** [comment]
Perfect!. We will then open a PR to the demos repository soon.
Thank you.

**Comment by christophfroehlich** [comment]
@saikishor there is an existing PR for a chained controller example: https://github.com/ros-controls/ros2_control_demos/pull/162

Will your contribution replace it (and work without any adaptions of upstream packages)?

**Comment by saikishor** [comment]
@christophfroehlich Thanks for the reference to the existing example. 

As far as I understand, that example PR shows how to launch and setup the controller chaining for an existing set of controllers, but there is no clear example of how to write a simple one (I'm aware of the existing admittance controller), but it is very complex for a newbie.  This controller itself will serve as a simple example. I think this controller is kinda similar to the https://github.com/ros-controls/ros2_controllers/pull/318 's (chainable_forward_controller)

**Comment by olivier-stasse** [comment]
I agree with @saikishor . Receiving the same kind of comments often, I am willing to help on the simple example.

**Comment by christophfroehlich** [comment]
@saikishor Ok, I understand. Nevertheless, I think a self-contained example including how to write a chained controller, as well as how to configure the chain, would be most valuable. This would be then a merge of this one and the existing one from @destogl

**Comment by saikishor** [comment]
@christophfroehlich Sounds good to me, then If I understood correctly, I will have to move this controller to the [ros-controls/ros2_control_demos](https://github.com/ros-controls/ros2_control_demos/) and maybe I can pick @destogl's commits and add changes on the top?. 

I believe all these changes should go inside the `example_10` folder structure right?

BTW, I am currently working on the controllers sorting, once I am done with that I will be happy to contribute to this.

**Comment by christophfroehlich** [comment]
We have a PR for example_10 and example_11 already, so your's would be example_12 then :wink: 
I suggest having a look on the [existing PR](https://github.com/ros-controls/ros2_control_demos/pull/162) but make a new one directly to the master branch, otherwise we have to approve/merge it twice. And pls follow the folder structure of the master branch.

**Comment by saikishor** [comment]
@christophfroehlich Sure. Thanks for the info. :+1:

**Comment by saikishor** [comment]
Hello @AndyZe!

You can close this PR, I've moved this example controller into the ros2_control_demos repo under [example_12](https://github.com/saikishor/ros2_control_demos/blob/master/example_12/doc/userdoc.rst).

Thank you,

Best Regards,
Sai

**Pull request closed without merging**
