### PR TITLE
Added tf_prefix to the left_wheel_names and right_wheel_names to solve Gazebo plugin issue.

### PR DESCRIPTION
**Pull request by suchetanrs**
The tf prefix is added to the odom_frame_id and the base_frame_id. However, it is not done to the left_wheel_names and right_wheel_names.

The differential drive controller is often used as a gazebo plugin like below. 
```
    <gazebo>
      <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
        <namespace>${robot_namespace}</namespace>
        <robot_param>robot_description</robot_param>
        <robot_param_node>robot_state_publisher</robot_param_node>
        <parameters>package://robot_description/config/robot_control.yaml</parameters>
      </plugin>
    </gazebo>
```

Since this is defined inside a xacro, the Rewritten yaml cannot be used to add namespaces to joints. Adding the namespace in the cpp file bypasses this issue.  In the PR, the convention is followed. That is, "robot_namespace/left_wheel_name". Please let me know if I need to change it in any other place. The modified changes solves my issue and seems to run correctly on the Gazebo simulator.

### CODE REVIEW

**Comment by bmagyar** [comment]
Please fix the issues reported by the "Format" stage by running `pre-commit run --all` locally and adding the changes to the PR

**Comment by suchetanrs** [comment]
Hi @bmagyar !
After fixing the format issues, I synced my fork with the master since its been a while. I now have a build error in rolling binary build / binary (main). All the other checks seem to pass. is it ok?

**Comment by christophfroehlich** [comment]
> Hi @bmagyar ! After fixing the format issues, I synced my fork with the master since its been a while. I now have a build error in rolling binary build / binary (main). All the other checks seem to pass. is it ok?

Rolling binary build on main fails because of an API break, which hasn't been synced yet. That's fine and unrelated to this PR.

**Comment by suchetanrs** [comment]
Ah I see! Thanks @christophfroehlich :D

**Comment by bmagyar** [comment]
Closing in favour of #1145

**Pull request closed without merging**
