### PR TITLE
use rolling mean from rcppmath

### PR DESCRIPTION
**Pull request by Karsten1987**
as per title.

With https://github.com/ros2/rcpputils/pull/133 being merged, we really should use rcppmath for the rolling mean.

### CODE REVIEW

**Comment by destogl** [comment]
Where is this actually used?

will this available for foxy, galactic, and rolling, or do we have to branch out.

**Comment by Karsten1987** [comment]
you need to branch out, I don't think it's getting backported to any existing distros. And this goes back to the discussion we had in the last WG meeting, that I'd really appreciate having master being the development branch.

**Review by destogl — APPROVED** [review]
It looks good.

**Comment by bmagyar** [comment]
Thanks, love to see PRs with a negative balance ;) 
Not long until branching, this goes on the wait list until then.

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
waiting a little more on https://github.com/ros2/rcpputils/issues/157

**Comment by bmagyar** [comment]
Finally merging!

**Pull request merged**
