### PR TITLE
Fix tests for using new `get_node_options` API

### PR DESCRIPTION
**Pull request by saikishor**
Needs: https://github.com/ros-controls/ros2_control/pull/1169

This PR adds fixes to the tests to support using the new `get_node_options` API that is present inside the controller interface

### CODE REVIEW

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
LGTM, but please extend also the [tutorial on writing new controllers](https://control.ros.org/master/doc/ros2_controllers/doc/writing_new_controller.html) to announce the new possibility.

**Comment by saikishor** [comment]
> LGTM, but please extend also the [tutorial on writing new controllers](https://control.ros.org/master/doc/ros2_controllers/doc/writing_new_controller.html) to announce the new possibility.

@christophfroehlich Done

**Review by christophfroehlich — APPROVED** [review]

**Review by bmagyar — APPROVED** [review]

**Comment by saikishor** [comment]
@bmagyar I'm fixing it now. I will push them in few min

**Comment by saikishor** [comment]
@bmagyar the semi-binary builds are passing now!

**Pull request merged**
