### PR TITLE
Add publish_rate option for diff_drive_controller (Foxy)

### PR DESCRIPTION
**Pull request by BenjaminHug8**
This PR add a `publish_rate` option for the `diff_drive_controller` in order to limit the publication on the `/odom` and `/tf` topics.

This solve request #274 for `Foxy`

### CODE REVIEW

**Comment by BenjaminHug8** [comment]
As described [in this request](https://github.com/ros-controls/ros2_controllers/issues/274#issuecomment-992624979), we want to have this feature for `foxy`, `galactic` and `rolling`.
So let me know if I have to target a particular branch (only `foxy` or `master` branch) and the feature will be ported to the other branches or if I have to make a PR for each branch.

**Comment by bmagyar** [comment]
please always target the `master` branch first, I think backporting can be done automatically with mergify

**Comment by BenjaminHug8** [comment]
I created another PR on [master](https://github.com/ros-controls/ros2_controllers/pull/278) with this change. In case backporting is done with mergify I will close this PR.

**Review by bmagyar — APPROVED** [review]

**Review by bmagyar — CHANGES_REQUESTED** [review]
will share the fate of #278

**Comment by BenjaminHug8** [comment]
Closed as this feature is backported from #278

**Pull request closed without merging**
