### PR TITLE
Use Generic Steering Controller State Message in Steering Controllers Library

### PR DESCRIPTION
**Pull request by mbharatheesha**
I was reading through the code as a part of learning how to write a new steering controller. I understood that a new steering controller inherits from the SteeringControllersLibrary. But I also found the use of `Ackermannxxx` in the base class code for a status message and the same was being used in other steering controllers such as `BicycleSteeringController` and `TricycleSteeringController`. 

If I understood the inheritance and the code structure correctly, the SteerinControllersLibrary should be agnostic to the specifics of a steering controller that derives from it. Therefore, this PR introduces the following changes:

- Remove the use of `Ackermannxxx` declarations in the `SteeringControllersLibrary` base class and rename it to `SteeringControllerStateMsg`
- Modify the tests and state publishers to use the renamed declaration
- Remove `ackermann_msgs` dependency from `steering_controllers_library` package.

All tests for the modified packages were run successfully (locally).

### CODE REVIEW

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
LGTM, thanks for the cleanup.

According to our guidelines: Please target the PR to the master branch, and we will perform backports to iron+humble.

**Comment by bmagyar** [comment]
For humble and iron we can only deprecate the use of these messages. Full removal can be done on rolling

**Comment by christophfroehlich** [comment]
but it doesn't change anything for users, only inherited classes may be broken. we could maybe use the `[[deprecated]]` c++ qualifier if necessary.

**Comment by mbharatheesha** [comment]
Apologies for the late response. Thanks for your remarks. I will submit a new PR targeted at master later today.

**Pull request closed without merging**
