### PR TITLE
migrate to industrial_ci

### PR DESCRIPTION
**Pull request by ipa-mdl**
https://github.com/ros-industrial/industrial_ci/issues/390

### CODE REVIEW

**Comment by ipa-mdl** [comment]
looks like the build is broken for dashing

**Comment by Karsten1987** [comment]
dashing needs #7 to be merged first.

**Comment by ipa-mdl** [comment]
> dashing needs #7 to be merged first.

Only for #8. It is already used for the test.

**Comment by Karsten1987** [comment]
@ipa-mdl I think we've settled on github actions for the ros2 related packages.

**Comment by ipa-mdl** [comment]
>  I think we've settled on github actions for the ros2 related packages.

`industrial_ci` is also available as a Github Action ;)

**Comment by gavanderhoorn** [comment]
@ipa-mdl: Windows CI is what made AWS go for GH actions I believe (https://github.com/ros-controls/ros2_control/issues/21).

**Comment by bmagyar** [comment]
This is very much outdated so I'm lcosing it but feel free to submit a new one, the ros2ci didn't really convince me tbh

**Pull request closed without merging**
