### PR TITLE
[JTC] Allow ff_velocity_scale=0 without deprecated warning

### PR DESCRIPTION
**Pull request by christophfroehlich**
Otherwise I always got this warning when I used a PID controller without feedforward gain.

### CODE REVIEW

**Comment by bmagyar** [comment]
I'm even tempted to say we could remove the deprecation warning completely and not accept the old format. We shouldn't be dealing with Param handling that's not with the generate params library.

**Comment by christophfroehlich** [comment]
ok for me, I didn't want to question Denis' deprecation warning ;)

**Comment by bmagyar** [comment]
The point of deprecation warnings is to eventually break what they warn
people about

**Comment by destogl** [comment]
> ok for me, I didn't want to question Denis' deprecation warning ;)

Feel free to remove it :)

It was not very long in there, but hopefully at least one release cycle.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
