### PR TITLE
Use time argument on update function instead of node time

### LINKED ISSUE #290: joint_trajectory_controller should not use `now()` but rely on time passed in through the `update()` function
## Background

joint_trajectory_controller should not use `now()` but rely on time passed in through the `update()` function. 

The goal of this ticket is to remove the usage of `node_->now()` from `joint_trajectory_controller.cpp` e.g. [here](https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L171) and replace it with the `time` parameter passed in [here](https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L110). 

Any usage of `node_->now()` that is in the same call tree as `update()`, meaning it is a function called within `update()` should also be eliminated. If needed, extend those function's parameters with `time`.

## Instructions
Hi, this is a `good-first-issue` issue. This means we've worked to make it more legible to people who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

We're interested in helping you take the first step, and can answer questions and help you out along the way. Note that we're especially interested in contributions from underrepresented groups!

We know that creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this PR for someone new**, and looking through our general [bug](https://github.com/ros-controls/ros2_controllers/labels/bug) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 🗄️ **Create a local workspace** for making your changes and testing [following these instructions](https://docs.ros.org/en/foxy/Tutorials/Workspace/Creating-A-Workspace.html), for Step3 use "Download Source Code" section with [these instructions](https://ros-controls.github.io/control.ros.org/getting_started.html#compiling).

- [ ] 🍴 **Fork the repository** using the handy button at the top of the repository page and **clone** it into `~/ws_ros2_control/src/ros-controls/ros2_controllers`, [here is a guide that you can follow](https://guides.github.com/activities/forking/) (You will have to remove or empty the existing `ros2_controllers` folder before cloning your own fork)

- [ ] **Checkout a new branch** using `git checkout -b <branch_name>`

- [ ] 🤖 **Apply `pre-commit`** auto formatting, by running `pip3 install pre-commit` and running `pre-commit install` in the ros2_control repo.

- [ ] 💾 **Commit and Push** your changes

- [ ] 🔀 **Start a Pull Request** to request to merge your code into `master`. There are two ways that you can start a pull request:
1. If you are not familiar with GitHub or how to create a pull request, [here is a guide you can follow](https://guides.github.com/activities/hello-world/) on how GitHub works.

- [ ] 🏁 **Done** Ask in comments for a review :)

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it.

👥- **If someone seems stuck, offer them some help!**

### 🤔❓ Questions?

Don’t hesitate to ask questions or to get help if you feel like you are getting stuck. For example leave a comment below!
Furthermore, you find helpful resources here:
* [ROS2 Control Contribution Guide](https://ros-controls.github.io/control.ros.org/contributing.html)
* [ROS2 Tutorials](https://docs.ros.org/en/foxy/Tutorials.html)
* [ROS Answers](https://answers.ros.org/questions/)

**Good luck with your first issue!**

### PR DESCRIPTION
**Pull request by erickisos**
Closes #290

### CODE REVIEW

**Comment by peterdavidfagan** [comment]
@bmagyar @erickisos, I'll look to set some time aside this weekend to start taking a look at these changes.

**Comment by peterdavidfagan** [comment]
Hi @erickisos, 

I am still getting up to speed with the codebase and the `joint_trajectory_controller.cpp` script as a result I have not as of yet completed my review but hope to do so in the coming days. 

One note I came across was what looks like a typo in some of the variable names for instance [here](https://github.com/ros-controls/ros2_controllers/blob/427e86ba28fa53ee44974e7289c7c317ffa8d3d2/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L151). While minor I'd be happy to push a commit to clean this up if you agree this looks like a simple naming typo.

Also it looks like certain tests/checks are currently failing as you mentioned above. Once I get up to speed I can take a look at these also.

Have a great start to the new week and hopefully we can get these changes merged by the end of the upcoming week.

**Review by bmagyar — APPROVED** [review]
looks good to me!

**Comment by bmagyar** [comment]
The error you see on the CI has to do with the time we use in the tests. The different time source error appears when you are trying ot mix ROS time with system time or simulated time. Probably we don't use the right one to compare values in the tests.

**Comment by peterdavidfagan** [comment]
@bmagyar should we open a separate issue to review the CI tests? I haven't completely finished my review but in order to not slow things down (and since a maintainer already approved this pr) I will also approve this pr.

**Review by peterdavidfagan — APPROVED** [review]
The pull request successfully uses the time argument within update function where node time was previously used. 

Some CI tests cases are failing ([see here](https://github.com/ros-controls/ros2_controllers/pull/296#issuecomment-1050617186)) and there appears to be a minor typo in variable naming within joint_trajectory_controller.cpp script ([see here](https://github.com/ros-controls/ros2_controllers/pull/296#issuecomment-1046330515)). I will look to follow up on these points in subsequent issues.

Approving for now.

**Comment by erickisos** [comment]
Just in case, the `inteface` problem is solved now, I didn't check the problem with the RHEL verifications, but if you need help with that I can check that later on.

**Comment by bmagyar** [comment]
Ignore the RHEL issue, focus on this instead:

```
  >>>
- joint_trajectory_controller.OnlyVelocityTrajectoryControllers/TrajectoryControllerTestParameterized test_ignore_partial_old_trajectory/0
  <<< failure message
    unknown file
    C++ exception with description "can't compare times with different time sources" thrown in the test body.
  >>>
- joint_trajectory_controller.OnlyVelocityTrajectoryControllers/TrajectoryControllerTestParameterized test_ignore_partial_old_trajectory/1
  <<< failure message
    unknown file
    C++ exception with description "can't compare times with different time sources" thrown in the test body.
```

**Comment by erickisos** [comment]
Thanks @bmagyar let me check

**Review by destogl — APPROVED** [review]
Looking good thanks!

P.S. Thanks for the typo correction. Probably have introduced it :smile:

**Comment by peterdavidfagan** [comment]
> Looking good thanks!
> 
> P.S. Thanks for the typo correction. Probably have introduced it smile

Apologies I had exams so was away for a while, great to see this merged. Also happy to go through the codebase when I have the chance to, I'm only spotting minor items at the moment such as typos, hopefully I'll be able to help out further at some point in the future when I'm more familiar with the codebase.

**Pull request merged**
