### PR TITLE
Command final waypoint identically when traj_point_active_ptr_ is null

### PR DESCRIPTION
**Pull request by egordon**
Addresses #671

Contributions via pull requests are much appreciated. Before sending us a pull request, please ensure that:

1. Limited scope. Your PR should do one thing or one set of things. Avoid adding “random fixes” to PRs. Put those on separate PRs.
2. Give your PR a descriptive title. Add a short summary, if required.
3. Make sure the pipeline is green.
4. Don’t be afraid to request reviews from maintainers.
5. New code = new tests. If you are adding new functionality, always make sure to add some tests exercising the code and serving as live documentation of your original intention.

To send us a pull request, please:

- [ X ] Fork the repository.
- [ X ] Modify the source; please focus on the specific change you are contributing. If you also reformat all the code, it will be hard for us to focus on your change.
- [ X ] Ensure local tests pass. (`colcon test` and `pre-commit run` (requires you to install pre-commit by `pip3 install pre-commit`)
- [ X ] Commit to your fork using clear commit messages.
- [x] Send a pull request, answering any default questions in the pull request interface.
- [x] Pay attention to any automated CI failures reported in the pull request, and stay involved in the conversation.

### CODE REVIEW

**Comment by egordon** [comment]
Check 1 fails at rosdep (installing `ros-humble-generate-parameter-library`, not found), not sure how to fix.

I cannot reproduce the test failure on my machine:
```
<testcase name="position_error_normalized/0" value_param="({ &quot;position&quot; }, { &quot;position&quot; })" status="run" result="completed" time="0.259" timestamp="2023-06-16T10:33:34" classname="joint_trajectory_controller.PositionTrajectoryControllers/TrajectoryControllerTestParameterized" />
```

Can anybody else confirm?

**Comment by moriarty** [comment]
> Check 1 fails at rosdep (installing `ros-humble-generate-parameter-library`, not found), not sure how to fix.
> 
> I cannot reproduce the test failure on my machine:
> 
> ```
> <testcase name="position_error_normalized/0" value_param="({ &quot;position&quot; }, { &quot;position&quot; })" status="run" result="completed" time="0.259" timestamp="2023-06-16T10:33:34" classname="joint_trajectory_controller.PositionTrajectoryControllers/TrajectoryControllerTestParameterized" />
> ```
> 
> Can anybody else confirm?

@tylerjw :eyes: Is generate-parameter-library released to RHEL + Humble?

**Comment by bmagyar** [comment]
Is this also applicable to rolling and iron? Please open PRs against the master branch for fixes and indicate you'd like a humble backport.

**Comment by egordon** [comment]
@bmagyar Understood, closing and re-upping as a master push with backport request.

**Pull request closed without merging**
